package common


const (
	TOKEN_NUM_VALUE_ERROR   		= "TOKEN_NUM_VALUE_ERROR"
	PRICE_VALUE_ERROR 				= "PRICE_VALUE_ERROR"
	EXCHANGE_PAIR_NOT_SUPPORT		= "EXCHANGE_PAIR_CLOSED_TEMPORARY"
	EXCHANGE_PAIR_PRECISION_ERROR	= "EXCHANGE_PAIR_PRECISION_ERROR"
	USER_NOT_EXIST					= "USER_NOT_EXIST"
	USER_STATUS_ABNORMAL			= "USER_STATUS_ABNORMAL"
	USER_COIN_BALANCE_NOT_ENOUGH	= "USER_COIN_BALANCE_NOT_ENOUGH"
	USER_OPERATION_ERROR			= "USER_OPERATION_ERROR"
	OPERATE_TOO_FREQUENT_ERROR		= "OPERATION_TOO_FREQUENT_ERROR"
	ORDER_TYPE_VALUE_ERROR			= "ORDER_TYPE_VALUE_ERROR"
	DATE_FORMAT_ERROR 				= "DATE_FORMAT_ERROR"
	ORDER_HAVE_CANCELED_ERROR 		= "ORDER_HAVE_CANCELED_ERROR"
	ORDER_CANNOT_BE_CANCELED 		= "ORDER_CANNOT_BE_CANCELED"
	ORDER_NOT_EXIST_ERROR			= "ORDER_NOT_EXIST_ERROR"
	DATE_FILTER_INTERVAL_ERROR		= "DATE_FILTER_INTERVAL_ERROR"
	SYSTEM_EXCEPTION				= "SYSTEM_EXCEPTION"
	INTERFACE_CALL_OVER_LIMIT		= "INTERFACE_CALL_OVER_LIMIT"
	USER_TOKEN_ACCOUNT_NOT_CREATE	= "USER_TOKEN_ACCOUNT_NOT_CREATE"
	USER_COIN_ACCOUNT_NOT_CREATE	= "USER_COIN_ACCOUNT_NOT_CREATE"
	INTERFACE_CALL_TOO_FREQUENT		= "INTERFACE_CALL_TOO_FREQUENT"
	SIGNATURE_ERROR 				= "SIGNATURE_ERROR"
	ACCESS_KEY_IS_EMPTY				= "ACCESS_KEY_IS_EMPTY"
	ACCESS_KEY_IS_INVALID			= "ACCESS_KEY_IS_INVALID"
	SIGNATURE_METHOD_IS_EMPTY		= "SIGNATRUE_METHOD_IS_EMPTY"
	SIGNATURE_METHOD_NOT_SUPPORT	= "SIGNATURE_METHOD_ISNOT_SUPPORT"
	SIGNATURE_VERSION_IS_EMPTY		= "SIGNATURE_VERSION_IS_EMPTY"
	SIGNATURE_VERSION_VALUE_ERROR 	= "SIGNATURE_VERSION_VALUE_ERROR"
	TIMESTAMP_IS_EMPTY				= "TIMESTAMP_IS_EMPTY"
	SIGNATURE_VALUE_IS_EMPTY		= "SIGNATURE_VALUE_IS_EMPTY"
	ACCESS_IP_NOT_ALLOWED			= "ACCESS_IP_NOT_ALLOWED"
	REQUIRED_PARAM_IS_EMPTY			= "REQUIRED_PARAM_IS_EMPTY"
	PARAM_VALUE_ERROR				= "PARAM_VALLUE_ERROR"
	USER_TOKEN_BALANCE_NOT_ENOUGH	= "USER_TOKEN_BALANCE_NOT_ENOUGH"
	ORDER_CANCEL_FAILED				= "ORDER_CANCEL_FAILED"
	ORDER_ID_INVILD					= "ORDER_ID_INVILD"
	PLATFORM_CLOSED_TEMPORARY	    = "PLATFORM_CLOSED_TEMPORARY"
	EXCHANGE_SERVICE_CLOSED		    = "EXCHANGE_SERVICE_CLOSED_TEMPORARY"
)



















